name: Deploy with Terragrunt

on:
  pull_request:
    types:
      - synchronize
      - closed
      - opened
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  deploy-infra:
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    uses: devops-homelab/homelab-github-reusable-workflows/.github/workflows/tf-deploy.yaml@main
    secrets:
      DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      TF_VAR_git_username: ${{ secrets.ARGOCD_GIT_USERNAME }}
      TF_VAR_pat_token: ${{ secrets.ARGOCD_PAT_TOKEN }}
    with:
      config_file: config.env
