name: Deploy with Terragrunt

on:
  pull_request:
    types:
      - synchronize
      - closed
      - opened
    branches:
      - main

jobs:
  terragrunt-deploy:
    name: Terragrunt Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      id-token: write
      
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Load environment variables from file
      - name: Load Environment Variables
        id: load-env
        run: |
          source config.env
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "COMPONENT=$COMPONENT" >> $GITHUB_ENV
          echo "MODULE=$MODULE" >> $GITHUB_ENV

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5
          terraform_wrapper: false

      # Step 4: Install Terragrunt
      - name: Install Terragrunt
        run: |
          TERRAGRUNT_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r '.tag_name' | sed 's/v//')
          curl -L -o /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
          chmod +x /usr/local/bin/terragrunt

      # Step 5: Deploy with Terragrunt
      - name: Terragrunt Plan - ${{ env.COMPONENT }}/${{ env.MODULE }}
        if: ${{ github.event.pull_request.merged == false }}
        run: |
            terragrunt --terragrunt-working-dir live/${{ env.ENVIRONMENT }}/${{ env.COMPONENT }}/${{ env.MODULE }}/ init --terragrunt-non-interactive
            terragrunt --terragrunt-working-dir live/${{ env.ENVIRONMENT }}/${{ env.COMPONENT }}/${{ env.MODULE }}/ plan --terragrunt-non-interactive
    
      # Step 6: Deploy with Terragrunt
      - name: Terragrunt Apply - ${{ env.COMPONENT }}/${{ env.MODULE }}
        if: ${{ github.event.pull_request.merged == true }}
        run: |
            terragrunt --terragrunt-working-dir live/${{ env.ENVIRONMENT }}/${{ env.COMPONENT }}/${{ env.MODULE }}/ apply --terragrunt-non-interactive -auto-approve