name: Manual Deploy with Terragrunt

on: workflow_dispatch

jobs:
  deploy-infra:
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    uses: devops-homelab/homelab-github-reusable-workflows/.github/workflows/tf-deploy-dispatch.yaml@main
    secrets:
      DO_SPACES_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY_ID }}
      DO_SPACES_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_ACCESS_KEY }}
      DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      TF_VAR_git_username: ${{ secrets.ARGOCD_GIT_USERNAME }}
      TF_VAR_pat_token: ${{ secrets.ARGOCD_PAT_TOKEN }}
      TF_VAR_sso_client_id: ${{ secrets.ARGOCD_SSO_CLIENT_ID }}
      TF_VAR_sso_client_secret: ${{ secrets.ARGOCD_SSO_CLIENT_SECRET }}
    with:
      config_file: config.env
