name: Deploy with Terragrunt

on:
  pull_request:
    types:
      - synchronize
      - closed
      - opened
    branches:
      - main

jobs:
  deploy-infra:
    permissions: write-all
    uses: devops-homelab/homelab-github-reusable-workflows/.github/workflows/tf-deploy.yaml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
    with:
      config_file: config.env