name: Terratest

on:
  push:
    branches:
      - feature/terratest

jobs:
  load-env-vars:
    name: Load Environment Variables
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      id-token: write

    outputs:
      ENVIRONMENT: ${{ steps.load-env.outputs.ENVIRONMENT }}
      COMPONENT: ${{ steps.load-env.outputs.COMPONENT }}
      MODULE: ${{ steps.load-env.outputs.MODULE }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Load environment variables from file
      - id: load-env
        name: Load Environment Variables
        run: |
          source config.env
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "COMPONENT=$COMPONENT" >> $GITHUB_ENV
          echo "MODULE=$MODULE" >> $GITHUB_ENV
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "COMPONENT=$COMPONENT" >> $GITHUB_OUTPUT
          echo "MODULE=$MODULE" >> $GITHUB_OUTPUT

  terratest:
    runs-on: ubuntu-latest
    needs: load-env-vars

    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      ENVIRONMENT: ${{ needs.load-env-vars.outputs.ENVIRONMENT }}
      COMPONENT: ${{ needs.load-env-vars.outputs.COMPONENT }}
      MODULE: ${{ needs.load-env-vars.outputs.MODULE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_git_username: ${{ secrets.TF_VAR_git_username }}
      TF_VAR_pat_token: ${{ secrets.TF_VAR_pat_token }}
      TF_VAR_sso_client_id: ${{ secrets.TF_VAR_sso_client_id }}
      TF_VAR_sso_client_secret: ${{ secrets.TF_VAR_sso_client_secret }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          TERRAGRUNT_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r '.tag_name' | sed 's/v//')
          curl -L -o /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
          chmod +x /usr/local/bin/terragrunt

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod tidy

      - name: Run Terratest
        run: go test -v ./test