name: Terratest

on:
  push:
    branches:
      - feature/terratest

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod tidy

      - name: Run Terratest
        run: go test -v ./test